---
title: 'Imprint: Terms and Conditions + Privacy Policy'
comments: false
---

# geo:truth

**Nonprofit Research Project**

**Contact Information:** \
Email: admin\@geotruth.org \
Website: <https://geotruth.github.io>

**Represented by:** \
Rasha Elnimeiry, Executive Director and Founder\

**Registration Information:** \
Registered as a Nonprofit Organization in Minnesota, United States\
EIN Number: 99-2228070\

**Tax Information:** \
Tax Identification Number: 99-2228070\
Not yet recognized as a tax-exempt organization under Section 501(c)(3) of the Internal Revenue Code (for U.S.-based organizations).

**Responsible for Content (according to § 55 Abs. 2 RStV):** \
Rasha Elnimeiry

**Disclaimer:** \
The content of our website has been compiled with meticulous care and to the best of our knowledge. However, we cannot assume any liability for the up-to-dateness, completeness, or accuracy of any of the pages. Pursuant to § 7 para. 1 TMG (German Telemedia Act), we are responsible for our own content on these pages in accordance with general laws. However, pursuant to §§ 8 to 10 TMG, we are not obligated to monitor transmitted or stored external information. Once we have become aware of a specific infringement of the law, we will immediately remove the content in question. Any liability concerning this matter can only be assumed from the point in time at which the infringement becomes known to us.

**External Links:** \
Our website contains links to third-party websites ("external links"). As the content of these websites is not under our control, we cannot assume any liability for such external content. In all cases, the provider of information of the linked websites is liable for the content and accuracy of the information provided. At the point in time when the links were placed, no infringements of the law were recognizable to us. As soon as an infringement of the law becomes known to us, we will immediately remove the link in question.

**Copyright:** \
The content and works published on this website are governed by the copyright laws of \[Country\]. Any duplication, processing, distribution, or any form of commercialization of such material beyond the scope of the copyright law shall require the prior written consent of its respective author or creator.

# **Privacy Policy**

**geo:truth - Nonprofit Research Project**

**Effective Date:** August 1, 2019

**1. Introduction** geo:truth ("we", "our", "us") is committed to protecting and respecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website \[www.geotruth.org\], as well as your rights in relation to your personal data.

**2. Information We Collect** We may collect and process the following types of information about you:

-   **Personal Identification Information**: Name, email address, phone number, mailing address, etc.
-   **Technical Data**: IP address, browser type, operating system, referral source, length of visit, page views, and website navigation paths.
-   **Usage Data**: Information about how you use our website, products, and services.
-   **Communications**: Content of messages you send us, including emails and other forms of communication.

**3. How We Use Your Information** We use the information we collect in the following ways:

-   To provide, operate, and maintain our website.
-   To improve, personalize, and expand our website.
-   To understand and analyze how you use our website.
-   To develop new products, services, features,

If you have any concerns about our terms and conditions or privacy, please email us: admin\@geo:truth.org

------------------------------------------------------------------------
