---
title: "<br>Our Team"
comments: false
page-layout: full
---

\
\

<h2>Hi, I'm [Rasha]{.gradient_text}.</h2>


I am the Executive Director of geo:truth and a geospatial epidemiologist with experience in epidemiological research and R programming. I am passionate seeing equitable health for everyone. I specialize in geospatial and statistical analysis, using GIS tools to visualize data and uncover health disparities. At geo:truth, I lead efforts to leverage cutting-edge technology for promoting health equity and informed interventions. In my free time, I combine my love for food and coding by automating my hydroponic garden.


[My portfolio](/portfolio/rasha/index.html)

\
<h2>Hi, I'm [Amaka]{.gradient_text}.</h2>


I am the Research Assistant at geo:truth. I am a dedicated public health researcher, who holds a bachelors in Health Equity and Data Science from Rhodes College. Currently, I am pursuing my master’s degree at the Rollins Schools of Public Health at Emory University in the Department of Global Health and Data Science Certificate. I am passionate about health equity work as well data visualization and mapping. I am deeply committed to advancing my data science skills and connecting more  with the GIS community.


[My portfolio](/portfolio/amaka/index.html)

\
<h2>Hi, I'm [Zuhur]{.gradient_text}.</h2>

I am the Director of Research and Analytics of geo:truth and a medical laboratory and epidemiological research scientist. Passionate about health equity, I design and conduct research on health disparities, analyze complex biological data, and collaborate with healthcare providers and community organizations. With a strong background in lab operations and regulatory compliance, I also develop training programs for staff and volunteers. As an analyst at heart and a dedicated team player, I am committed to advancing geo:truth's mission of uncovering and addressing health disparities.



[My portfolio]( )

\



<h2>Hi, I'm [Jordan]{.gradient_text}.</h2>

</span> I am the Director of Programs and Impact of geo:truth and a trained medical technologist who also passionate about policy and advocacy and systemic change and positive impact. I oversee the development and implementation of research findings aimed at improving health equity through community empowerment and strategic initiatives. I am excited about translating research insights into acttional programs that adress health disparities. 


[My portfolio]( )
\

\

<!-- # Support Us -->
<!-- ```{=html} -->
<!-- <script  -->
<!--             type="text/javascript"  -->
<!--             src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js"  -->
<!--             data-name="bmc-button"  -->
<!--             data-slug="geotruth"  -->
<!--             data-color="#DDDDDD"  -->
<!--             data-emoji=""   -->
<!--             data-font="Poppins"  -->
<!--             data-text="Support Us with a Cup of Coffee"  -->
<!--             data-outline-color="#000000"  -->
<!--             data-font-color="#000000"  -->
<!--             data-coffee-color="#00A9A3"> -->
<!--         </script> -->
<!-- ``` -->
\

\

# What We Are Up To:

-   HIRING: Are you passionate about health equity? We need you!

\
\

------------------------------------------------------------------------

```{=html}
<h3>At geo:truth we are driven by the belief that <span style='text-decoration: underline;text-decoration-color: #00A9A3;'>truth is worth discovering.</span></h3>
```

------------------------------------------------------------------------

<audio controls autoplay loop>

<source src="/audio/videosudden.mp4" type="audio/mpeg">

Your browser does not support the audio tag.</audio>
