---
title: "</br>Research Talks + Publications"
excerpt: "A list of team publications."
toc-location: right
page-layout: full
---

Here's a list of our selected talks and publications where our team is involved. If available, you'll also find slides, related papers, and recordings. **Bold** font indicates team member.

------------------------------------------------------------------------

# Syndromic Surveillance

-   **Elnimeiry, R.**, Stepanov A., Pinks, K. (Mar 2020). [Surrogate for the Truth: Reexamination of North Dakota Traumatic Brain Injury Syndromic Data](pdf/slides_traumaticbraininjuryDQ.pdf).\
    Presented at the [CDC National Syndromic Surveillance Program, Community of Practice, Data Quality Subcommittee](https://cdn.ymaws.com/www.cste.org/resource/resmgr/nssp/Traumatic_Brain_Injury_DQ.pdf) meeting. \[Committee Presentation – Spatial Distribution of Chief Compliant Quality across ND\]

-   **Elnimeiry, R.**, Stepanov A., Pinks, K., (Nov 2019) **Syndrome/Case Definition for Traumatic Brain Injury: The Journey From Data Request, Developing Definition, Analysis and Use**\
    Presented at *National Syndromic Surveillance Program, Community of Practice, Syndrome Definition Subcommittee Meeting*

\

# Perinatal Health

-   **Elnimeiry, R.** (January, 2020) **Perinatal Health: Learning from Population Based Surveys**\
    Presented at *North Dakota Title V\| Maternal Child Health Meeting*

\

# Opioid - Oral Health Epidemiology

-   **Elnimeiry, R.** (Dec 2019) **Results of the Opioid Dental Survey and Utilization of Prescription Drug Monitoring Program**\
    Presented at *North Dakota Dental Association Mid-Winter Annual Meeting*

##### Publications

```{=html}
<p class="text-left">
<a class="btn btn-primary btn-lg cv-download" href="/portfolio/nd-dental-pain-management.pdf" target="_blank">
<i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Report
</a>
<div class="embed-container">
<iframe src="/portfolio/nd-dental-pain-management.pdf#toolbar=0" style="border: 0.5px">
</iframe>
</div>
</p>
```
# Wastewater-based Epidemiology

##### Publications

```{=html}
<p class="text-left">
<a class="btn btn-primary btn-lg cv-download" href="/portfolio/structured-ethical-review-for-wastewater.pdf" target="_blank">
<i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Report
</a>
<div class="embed-container">
<iframe src="/portfolio/structured-ethical-review-for-wastewater.pdf#toolbar=0" style="border: 0.5px">
</iframe>
</div>
</p>
```
\
\
<audio controls autoplay loop>

<source src="/audio/videosudden.mp4" type="audio/mpeg">

Your browser does not support the audio tag.</audio>
